# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Awards
    url: '#award'
    weight: 20
  - name: Publications
    url: '#featured'
    weight: 30
  - name: Patents
    url: '#patent'
    weight: 40
  - name: Experience
    url: '#experience'
    weight: 50
  - name: Projects
    url: '#projects'
    weight: 60
  - name: Gallery
    url: '#gallery'
    weight: 70
  - name: Blogs
    url: 'https://utkarsh-blogs.netlify.app/'
    weight: 80
  
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
